file = open("bucket_list.txt","w")
file.write("I want to visit Spain\n")
file.write("I want to visit the Swiss Alps\n")
file.write("I want to visit Japan\n")
file.close()
file = open("bucket_list.txt","r")
content = file.read()
print(content)
file.close()
file = open("bucket_list.txt","r")
lines = file.readlines()
print(len(lines))
file.close()
file = open("bucket_list.txt","a")
file.write("I want to make money\n")
file.write("I want to go skiing\n")
file.close()
file = open("bucket_list.txt","r")
print(file.read())
file.close()